# unfortunately broken because playwright binaries are not compiled and installed for alpine
FROM alpine:3.15

ARG NODE_ENV
ENV NODE_ENV=$NODE_ENV

COPY ./ /opt
WORKDIR /opt

RUN apk add --no-cache --update --upgrade nodejs yarn npm

RUN yarn install --production=false && \
    yarn eslint && \
    yarn audit && \
    yarn build && \
    rm -rf .parcel-cache && \
    yarn test && \
    yarn cache clean && \
    rm -rf node_modules

CMD yarn serve