name: pr

on:
  pull_request:
    branches:
      - 'master'

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        env:
          NODE_ENV: production
        run: |
          DOCKER_BUILDKIT=1 docker build --rm --force-rm --no-cache .
