name: commit

on:
  push:
    branches:
      - main

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        env:
          NODE_ENV: production
        run: |
          DOCKER_BUILDKIT=1 docker build --rm --force-rm --no-cache --build-arg NODE_ENV=production .

#      - name: build and deploy
#        env:
#          ENV: staging
#          HOST: my-staging-host.com
#          PEM: ${{secrets.PEM_STAGING}}
#          DOCKERHUB_USER: damianobarbati
#          DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
#        run: |
#          eval `ssh-agent -s`
#          ssh-add - <<< "$PEM"
#          mkdir ~/.ssh
#          ssh-keyscan -p 22 -H "$HOST" >> ~/.ssh/known_hosts
#
#          docker login docker.io --username "$DOCKERHUB_USER" --password "$DOCKERHUB_TOKEN"
#          sh deploy.sh "$ENV"
