name: commit

on:
  push:
    branches:
      - 'master'

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
            node-version: '14'

      - name: deploy
        env:
            VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}
        run: |
          NODE_ENV=staging yarn build
          npx vercel --token=$VERCEL_TOKEN deploy --env NODE_ENV=staging --confirm .
