name: pr

on:
  pull_request:
    branches:
      - 'master'

jobs:
  deploy-pr:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: deploy
        run: npx vercel --env NODE_ENV=staging
