name: pr

on:
  pull_request:
    branches:
      - 'master'

jobs:
  deploy-branch:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
            node-version: '14'

      - name: deploy
        env:
            VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}
        run: |
          yarn install
          NODE_ENV=staging yarn build
          npx vercel --token=$VERCEL_TOKEN deploy --env NODE_ENV=staging --confirm .
