name: pr

on:
  pull_request:
    branches:
      - 'master'

jobs:
  deploy-branch:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: deploy
        env:
            VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}
        run: |
          NODE_ENV=staging yarn build
          npx vercel --token=$VERCEL_TOKEN deploy --env NODE_ENV=staging --confirm .
