name: tag

on:
  push:
    tags:
      - '**'

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
            node-version: '14'

      - name: deploy
        env:
            VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}
        run: |
          yarn install
          NODE_ENV=production yarn build
          cat vercel.json | jq '. | .alias=["damianobarbati.com"]' > temp.json && mv temp.json vercel.json
          npx vercel --token=$VERCEL_TOKEN deploy --env NODE_ENV=production --prod --confirm .
