name: tag

on:
  push:
    tags:
      - '**'

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: deploy
        env:
            VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}
        run: npx vercel --token=$VERCEL_TOKEN deploy --env NODE_ENV=production --prod --confirm .
